export const CRYPTO_TICKER_MAP: Record<string, string> = {
  BTC: 'bitcoin',
  ETH: 'ethereum',
  BNB: 'binancecoin',
  SOL: 'solana',
  ADA: 'cardano',
  DOT: 'polkadot',
  MATIC: 'matic-network',
  LINK: 'chainlink',
  LTC: 'litecoin',
  XRP: 'ripple',
  DOGE: 'dogecoin',
  AVAX: 'avalanche-2',
  SHIB: 'shiba-inu',
  TRX: 'tron',
  TON: 'toncoin',
  USDT: 'tether',
  UNI: 'uniswap',
};
